// Ethiopian Mock Data for AgroGebeya

export const ethiopianFarmers = [
  {
    id: '1',
    name: 'አበበ ገብረስላሴ',
    englishName: 'Abebe Gebreselassie',
    email: 'abebe.gebreselassie@agrogebeya.com',
    location: 'Addis Ababa',
    phone: '+251911234567',
    region: 'Addis Ababa',
    farmSize: 15,
  },
  {
    id: '2',
    name: 'ተፍቶ ዘሪ',
    englishName: 'Teffo Zeri',
    email: 'teffo.zeri@agrogebeya.com',
    location: 'Hawassa',
    phone: '+251912345678',
    region: 'SNNPR',
    farmSize: 25,
  },
  {
    id: '3',
    name: 'ደምሴ ዓለም',
    englishName: 'Demse Alem',
    email: 'demse.alem@agrogebeya.com',
    location: 'Jimma',
    phone: '+251913456789',
    region: 'Oromia',
    farmSize: 20,
  },
  {
    id: '4',
    name: 'ዩሕዋስ ታደሰ',
    englishName: 'Yuhwas Tadesse',
    email: 'yuhwas.tadesse@agrogebeya.com',
    location: 'Bahir Dar',
    phone: '+251914567890',
    region: 'Amhara',
    farmSize: 18,
  },
]

export const ethiopianRetailers = [
  {
    id: 'r1',
    name: 'ታደሰ አባተ',
    englishName: 'Tadesse Abate',
    email: 'tadesse.abate@freshmarket.com',
    location: 'Dire Dawa',
    phone: '+251921234567',
    businessName: 'Fresh Market Ethiopia',
    storeCount: 3,
  },
  {
    id: 'r2',
    name: 'ሁባ ታደላ',
    englishName: 'Huba Tadla',
    email: 'huba.tadla@greenmarket.com',
    location: 'Adama',
    phone: '+251922345678',
    businessName: 'Green Market LLC',
    storeCount: 2,
  },
  {
    id: 'r3',
    name: 'ቤርሃነ ሳሙ',
    englishName: 'Berhane Samu',
    email: 'berhane.samu@promarket.com',
    location: 'Mekelle',
    phone: '+251923456789',
    businessName: 'Pro Market Tigray',
    storeCount: 4,
  },
]

export const ethiopianProducts = [
  {
    id: '1',
    amharicName: 'ቲማቲም ኦርጋኒክ',
    englishName: 'Organic Tomatoes',
    category: 'Vegetables',
    price: 25,
    unit: 'KG',
    location: 'Addis Ababa',
    farmer: 'አበበ ገብረስላሴ',
  },
  {
    id: '2',
    amharicName: 'ሽንኩርት አዲስ',
    englishName: 'Fresh Onions',
    category: 'Vegetables',
    price: 30,
    unit: 'KG',
    location: 'Hawassa',
    farmer: 'ተፍቶ ዘሪ',
  },
  {
    id: '3',
    amharicName: 'ድንች ቀይ',
    englishName: 'Red Potatoes',
    category: 'Vegetables',
    price: 20,
    unit: 'KG',
    location: 'Jimma',
    farmer: 'ደምሴ ዓለም',
  },
  {
    id: '4',
    amharicName: 'ካሮት ወርደ',
    englishName: 'Garden Carrots',
    category: 'Vegetables',
    price: 22,
    unit: 'KG',
    location: 'Bahir Dar',
    farmer: 'ዩሕዋስ ታደሰ',
  },
  {
    id: '5',
    amharicName: 'ጎመን አዲስ',
    englishName: 'Fresh Cabbage',
    category: 'Vegetables',
    price: 15,
    unit: 'KG',
    location: 'Mekelle',
    farmer: 'ሃይሉ ግርማ',
  },
  {
    id: '6',
    amharicName: 'ሙዝ ሙቅ',
    englishName: 'Ripe Bananas',
    category: 'Fruits',
    price: 35,
    unit: 'Dozen',
    location: 'Dire Dawa',
    farmer: 'ወርቁ ሻርም',
  },
  {
    id: '7',
    amharicName: 'ብርቱካን ጣፈጥ',
    englishName: 'Sweet Oranges',
    category: 'Fruits',
    price: 40,
    unit: 'KG',
    location: 'Adama',
    farmer: 'በእንደታ ሳምራ',
  },
  {
    id: '8',
    amharicName: 'ጤፍ ነጩ',
    englishName: 'White Wheat',
    category: 'Grains',
    price: 18,
    unit: 'KG',
    location: 'Arsi Zone',
    farmer: 'ሙስተ ጥበብ',
  },
  {
    id: '9',
    amharicName: 'ጤፍ ቀይ',
    englishName: 'Red Teff',
    category: 'Grains',
    price: 45,
    unit: 'KG',
    location: 'South Wollo',
    farmer: 'አስራት ግብረ',
  },
  {
    id: '10',
    amharicName: 'ወተት አዲስ',
    englishName: 'Fresh Milk',
    category: 'Dairy',
    price: 50,
    unit: 'Litre',
    location: 'Addis Ababa',
    farmer: 'ኖሪ ዲሪ ተባብ',
  },
]

export const ethiopianCities = [
  'Addis Ababa',
  'Dire Dawa',
  'Adama',
  'Hawassa',
  'Mekelle',
  'Bahir Dar',
  'Jimma',
  'Arsi Zone',
  'Wollega',
  'South Wollo',
  'Gimbi',
  'Durame',
]

export const ethiopianRegions = [
  'Addis Ababa',
  'Amhara',
  'Oromia',
  'SNNPR',
  'Tigray',
  'Benishangul-Gumuz',
  'Gambela',
  'Harari',
  'Afar',
  'Dire Dawa',
  'Somali',
]
